---
  extends:
    - next/core-web-vitals
    - prettier
  plugins:
    - prettier
  rules:
    prettier/prettier:
      - error
    camelcase:
      - error
      - ignoreImports: true
  overrides:
    - files:
        - '**/*.test.{tsx,ts,js,jsx}'
      globals:
        describe: true
        it: true
        expect: true
